import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import NavbarLogout from './navbar-logout'
import NavbarCustom from './navbar-custom'
import NavbarSeller from './navbar-seller'
import Footer from './footer'
import Section from './section'

export default function MainLayout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-container-fluid">
        <header className="row">
          <NavbarLogout />
          {/* <NavbarCustom /> */}
          {/* <NavbarSeller /> */}
        </header>
        <main className="row">
          {children}
          {/* <div className="section">{children}</div> */}
        </main>
        <Footer />
      </div>
    </>
  )
}
